
spring:
  application:
    name: dubbo-consumer
    version: 1.0
server:
  port: 9091

dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
  protocol:
    id: dubbo
    name: dubbo
#    port: 20882
#    status: server
  registry:
    protocol: zookeeper
    address: 10.1.51.96:2181
    id: zookeeper-registry

endpoints:
  dubbo:
    enabled: true

management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-servces:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-refrences:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'


