spring:
  application:
    name: dubbo-provider
    version: 1.0

  ### activemq config
  activemq:
    broker-url: tcp://10.1.51.96:61616 # activemq broker Url config
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
    queue-name: test.msg.queue
    out-queue-name: test.msg.out-queue
    topic-name: test.msg.topic

  ### elasticsearch config
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 10.1.51.96:9300
      repositories:
        enabled: true

server:
  port: 9090

dubbo:
  scan:
    basePackages: com.example.provider.service
  application:
    id: dubbo-provider
    name: dubbo-provider
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: true
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
    status: server
  registry:
    protocol: zookeeper
    address: 10.1.51.96:2181
#    address: 10.1.51.96:2181,10.1.51.96:2182
    id: zookeeper-registry
  provider:
    loadbalance: consistenthash


#  registries:
#    aa:
#      address: zookeeper://10.1.51.96:2181
#    bb:
#      address: zookeeper://10.1.51.96:2182
#  registry:
#    protocol: zookeeper
#    address: zookeeper://10.1.51.96:2181?backup=10.1.51.96:2182
#    id: zookeeper-registry


motan:
  registry:
    regProtocol: zookeeper
    address: 10.1.51.96:2181
    requestTimeout: 1000
    connectTimeout: 3000
  protocol:
    name: motan
    minWorkThread: 20
    maxWorkThread: 50
    filter: statistic
  annotation:
    package: com.example.provider.motan
  server:
    export: 'motan:9999'
    group: motangroup
    registry: registry

##endpoint
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-servces:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-refrences:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.elasticsearch: info
    org.springframework: info
    org.springframework.data.elasticsearch.repository: info
  file: log\provider.log

