spring:
  application:
    name: dubbo-provider
    version: 1.0

  ### activemq config
  activemq:
    broker-url: tcp://10.1.51.96:61616 # activemq broker Url config
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
    queue-name: test.msg.queue
    out-queue-name: test.msg.out-queue
    topic-name: test.msg.topic

  ### elasticsearch config
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 10.1.51.96:9300
      repositories:
        enabled: true

  kafka:
    listener:
      poll-timeout: 1500
      concurrency: 10
      batch-listener: true
    template:
      default-topic: monitor-data
    producer:
      bootstrap-servers: 10.1.51.240:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
    consumer:
      group-id: group-2
      bootstrap-servers: 10.1.51.240:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
      auto:
        offset:
          reset: latest
      enable:
        auto:
          commit: true

server:
  port: 9080

dubbo:
  scan:
    basePackages: com.example.provider.service
  application:
    id: dubbo-provider
    name: dubbo-provider
    qos-enable: true
    qos-port: 33332
    qos-accept-foreign-ip: true
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
    status: server
  registry:
    protocol: zookeeper
    address: 10.1.51.96:2181
    id: zookeeper-registry
  provider:
    loadbalance: consistenthash



motan:
  registry:
    regProtocol: zookeeper
    address: 10.1.51.96:2181
    requestTimeout: 1000
    connectTimeout: 3000
  protocol:
    name: motan
    minWorkThread: 20
    maxWorkThread: 50
    filter: statistic
  annotation:
    package: com.example.provider.motan
  server:
    export: 'motan:9998'
    group: motangroup
    registry: registry

##endpoint
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-servces:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-refrences:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.elasticsearch: info
    org.springframework: info
    org.springframework.data.elasticsearch.repository: info
  file: log\provider.log

